pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments:  true
  params: count=countSql

spring:
  datasource:
      url:  jdbc:mysql://172.17.16.6:3306/theway?useUnicode=true&autoReconnect=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false&serverTimezone=Asia/Shanghai
      username:  root
      password:  Theway123
      driver-class-name: com.mysql.jdbc.Driver

