package com.wangshangyi.tracker;

import java.util.ArrayList;
import java.util.Arrays;

public class Traceno {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traceNo.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traceNo.wid
     *
     * @mbg.generated
     */
    private String wid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traceNo.headNo
     *
     * @mbg.generated
     */
    private String headno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traceNo.tailNo
     *
     * @mbg.generated
     */
    private String tailno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traceNo.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traceNo.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traceNo.id
     *
     * @return the value of traceNo.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traceNo.id
     *
     * @param id the value for traceNo.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traceNo.wid
     *
     * @return the value of traceNo.wid
     *
     * @mbg.generated
     */
    public String getWid() {
        return wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traceNo.wid
     *
     * @param wid the value for traceNo.wid
     *
     * @mbg.generated
     */
    public void setWid(String wid) {
        this.wid = wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traceNo.headNo
     *
     * @return the value of traceNo.headNo
     *
     * @mbg.generated
     */
    public String getHeadno() {
        return headno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traceNo.headNo
     *
     * @param headno the value for traceNo.headNo
     *
     * @mbg.generated
     */
    public void setHeadno(String headno) {
        this.headno = headno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traceNo.tailNo
     *
     * @return the value of traceNo.tailNo
     *
     * @mbg.generated
     */
    public String getTailno() {
        return tailno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traceNo.tailNo
     *
     * @param tailno the value for traceNo.tailNo
     *
     * @mbg.generated
     */
    public void setTailno(String tailno) {
        this.tailno = tailno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traceNo.comment
     *
     * @return the value of traceNo.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traceNo.comment
     *
     * @param comment the value for traceNo.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traceNo.status
     *
     * @return the value of traceNo.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traceNo.status
     *
     * @param status the value for traceNo.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traceNo
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", wid=").append(wid);
        sb.append(", headno=").append(headno);
        sb.append(", tailno=").append(tailno);
        sb.append(", comment=").append(comment);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traceNo
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Traceno other = (Traceno) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getWid() == null ? other.getWid() == null : this.getWid().equals(other.getWid()))
            && (this.getHeadno() == null ? other.getHeadno() == null : this.getHeadno().equals(other.getHeadno()))
            && (this.getTailno() == null ? other.getTailno() == null : this.getTailno().equals(other.getTailno()))
            && (this.getComment() == null ? other.getComment() == null : this.getComment().equals(other.getComment()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traceNo
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getWid() == null) ? 0 : getWid().hashCode());
        result = prime * result + ((getHeadno() == null) ? 0 : getHeadno().hashCode());
        result = prime * result + ((getTailno() == null) ? 0 : getTailno().hashCode());
        result = prime * result + ((getComment() == null) ? 0 : getComment().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table traceNo
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        wid("wid", "wid", "VARCHAR", false),
        headno("headNo", "headno", "VARCHAR", false),
        tailno("tailNo", "tailno", "VARCHAR", false),
        comment("comment", "comment", "VARCHAR", true),
        status("status", "status", "VARCHAR", true);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table traceNo
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table traceNo
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table traceNo
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table traceNo
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table traceNo
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table traceNo
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table traceNo
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table traceNo
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table traceNo
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table traceNo
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table traceNo
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table traceNo
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table traceNo
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table traceNo
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table traceNo
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table traceNo
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}